HalfDjangoProject/pizzas/urls.py
"""Define url patterns for pizzas"""

from django.urls import path

from . import views


app_name = 'pizzas'
urlpatterns = [
	# Home page.
	path('', views.index, name='index'),
	# Page that shows all the pizzas.
	path('pizza_names/', views.pizzas, name='pizza_names'),
	# Detail page for a single topic.
	path('pizza_names/<int:pizza_id/', views.pizza, name='pizza'),
]

HalfDjangoProject/pizzeria/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('pizzas.urls'))
]

HalfDjangoProject/pizzas/models.py
from django.db import models


class Pizza(models.Model):
	name = models.CharField(max_length=200)
	date_added = models.DateTimeField(auto_now_add=True)

	def __str__(self):
		return self.name


class Topping(models.Model):
	name = models.TextField()
	pizza = models.ForeignKey(Pizza, on_delete=models.CASCADE)

	def __str__(self):
		if len(self.name) > 50:
			return f"{self.name}..."
		else:
			return self.name

HalfDjangoProject/pizzas/views.py
from django.shortcuts import render

from .models import Pizza


def index(request):
	""" The home page for pizzeria."""
	return render(request, 'pizzas/index.html')

def pizzas(request):
	"""show all pizzas"""
	pizzas = Pizza.objects.order_by('date_added')
	context = {'pizzas': pizzas}
	return render(request, 'pizzas/pizza_names.html', context)

def pizza(request, pizza_id):
	"""Show a single pizza and all its toppings."""
	pizza = Pizza.objects.get(id=pizza_id)
	toppings = pizza.topping_set.order_by('-date_added')
	context = {'pizza': pizza, 'toppings': toppings}
	return render(request, 'pizzas/pizza_name.html', context)

HalfDjangoProject/pizzas/templates/pizzas/base.html
<p>
  <a href="{% url 'pizzas:index' %}">Pizzeria</a> - 
  <a href="{% url 'pizzas:pizza_names' %}">Pizzas</a>
</p>

{% block content %}{% endblock content %}

HalfDjangoProject/pizzas/templates/pizzas/index.html
{% extends "pizzas/base.html" %}

{% block content %}

<p>Pizzaria helps you to find the best pizza in the history of pizzas!!!</p>

{% endblock content %}

HalfDjangoProject/pizzas/templates/pizzas/pizza_name.html
{% extends 'pizzas/base.html' %}

{% block content %}

  <p>Pizza: {{ pizza }}</p>

  <p>Toppings:</p>
  <ul>
  {% for topping in toppings %}
    <li>
      <p>{{ topping.date_added|date:'M d, Y H:i' }}</p>
      <p>{{ topping.text|linebreaks }}</p>
    </li>
  {% empty %}
    <li>There are no toppings in this pizza yet. :P</li>
  {% endfor %}
  </ul>

{% endblock content %}

HalfDjangoProject/pizzas/templates/pizzas/pizza_names.html
{% extends "pizzas/base.html" %}

{% block content %}

  <p>Pizzas</p>

  <ul>
  	{% for pizza in Pizzas %}
  	  <li>
  	    <a href="{% url 'pizzas:pizza_name' pizza.id %}">{{ pizza }}</a>
  	  </li>
  	{% empty %}
  	  <li>No pizza have been added yet.</li>
  	{% endfor %}
  </ul>

{% endblock content %}